[package]
name = "gl-bug-tester"
version = "0.1.0"
authors = ["Dzmitry Malyshau <dmalyshau@mozilla.com>"]
edition = "2018"

[dependencies]
colorful = "0.2"
glow = "0.4"
surfman = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.6"
